// Code generated by "stringer -type=MediaType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeCollection-1]
	_ = x[TypeSeries-2]
	_ = x[TypeTVShow-3]
	_ = x[TypeMovie-4]
}

const _MediaType_name = "TypeUnknownTypeCollectionTypeSeriesTypeTVShowTypeMovie"

var _MediaType_index = [...]uint8{0, 11, 25, 35, 45, 54}

func (i MediaType) String() string {
	if i < 0 || i >= MediaType(len(_MediaType_index)-1) {
		return "MediaType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MediaType_name[_MediaType_index[i]:_MediaType_index[i+1]]
}
