package download

import (
	"context"
	"encoding/json"
	"reflect"
	"testing"
)

func encodeFFProbeJson(s string) *FFProbeOutput {
	r := FFProbeOutput{}
	err := json.Unmarshal([]byte(s), &r)
	if err != nil {
		return nil
	}
	return &r
}

func TestProbeStream(t *testing.T) {
	type args struct {
		url string
	}
	tests := []struct {
		name    string
		args    args
		want    *FFProbeOutput
		wantErr bool
	}{
		{
			name: "hls",
			args: args{
				url: "http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8",
			},
			want: encodeFFProbeJson(`{
				"streams": [
					{
						"index": 0,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "Baseline",
						"codec_type": "video",
						"codec_time_base": "0/2",
						"codec_tag_string": "[27][0][0][0]",
						"codec_tag": "0x001b",
						"width": 640,
						"height": 360,
						"coded_width": 640,
						"coded_height": 360,
						"has_b_frames": 0,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "16:9",
						"pix_fmt": "yuv420p",
						"level": 30,
						"color_range": "tv",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "false",
						"nal_length_size": "0",
						"r_frame_rate": "30000/1001",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "688301"
						}
					},
					{
						"index": 1,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/48000",
						"codec_tag_string": "[15][0][0][0]",
						"codec_tag": "0x000f",
						"sample_fmt": "fltp",
						"sample_rate": "48000",
						"channels": 2,
						"channel_layout": "stereo",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "688301"
						}
					},
					{
						"index": 2,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "Baseline",
						"codec_type": "video",
						"codec_time_base": "0/2",
						"codec_tag_string": "[27][0][0][0]",
						"codec_tag": "0x001b",
						"width": 400,
						"height": 224,
						"coded_width": 400,
						"coded_height": 224,
						"has_b_frames": 0,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "25:14",
						"pix_fmt": "yuv420p",
						"level": 30,
						"color_range": "tv",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "false",
						"nal_length_size": "0",
						"r_frame_rate": "10000/1001",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 27027,
						"start_time": "0.300300",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "165135"
						}
					},
					{
						"index": 3,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/48000",
						"codec_tag_string": "[15][0][0][0]",
						"codec_tag": "0x000f",
						"sample_fmt": "fltp",
						"sample_rate": "48000",
						"channels": 2,
						"channel_layout": "stereo",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 27027,
						"start_time": "0.300300",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "165135"
						}
					},
					{
						"index": 4,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "Baseline",
						"codec_type": "video",
						"codec_time_base": "0/2",
						"codec_tag_string": "[27][0][0][0]",
						"codec_tag": "0x001b",
						"width": 640,
						"height": 360,
						"coded_width": 640,
						"coded_height": 360,
						"has_b_frames": 0,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "16:9",
						"pix_fmt": "yuv420p",
						"level": 30,
						"color_range": "tv",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "false",
						"nal_length_size": "0",
						"r_frame_rate": "15000/1001",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 18018,
						"start_time": "0.200200",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "262346"
						}
					},
					{
						"index": 5,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/48000",
						"codec_tag_string": "[15][0][0][0]",
						"codec_tag": "0x000f",
						"sample_fmt": "fltp",
						"sample_rate": "48000",
						"channels": 2,
						"channel_layout": "stereo",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 18018,
						"start_time": "0.200200",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "262346"
						}
					},
					{
						"index": 6,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "Baseline",
						"codec_type": "video",
						"codec_time_base": "0/2",
						"codec_tag_string": "[27][0][0][0]",
						"codec_tag": "0x001b",
						"width": 400,
						"height": 224,
						"coded_width": 400,
						"coded_height": 224,
						"has_b_frames": 0,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "25:14",
						"pix_fmt": "yuv420p",
						"level": 30,
						"color_range": "tv",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "false",
						"nal_length_size": "0",
						"r_frame_rate": "30000/1001",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "481677"
						}
					},
					{
						"index": 7,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/48000",
						"codec_tag_string": "[15][0][0][0]",
						"codec_tag": "0x000f",
						"sample_fmt": "fltp",
						"sample_rate": "48000",
						"channels": 2,
						"channel_layout": "stereo",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "481677"
						}
					},
					{
						"index": 8,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "Baseline",
						"codec_type": "video",
						"codec_time_base": "0/2",
						"codec_tag_string": "[27][0][0][0]",
						"codec_tag": "0x001b",
						"width": 640,
						"height": 360,
						"coded_width": 640,
						"coded_height": 360,
						"has_b_frames": 0,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "16:9",
						"pix_fmt": "yuv420p",
						"level": 30,
						"color_range": "tv",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "false",
						"nal_length_size": "0",
						"r_frame_rate": "30000/1001",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "1308077"
						}
					},
					{
						"index": 9,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/48000",
						"codec_tag_string": "[15][0][0][0]",
						"codec_tag": "0x000f",
						"sample_fmt": "fltp",
						"sample_rate": "48000",
						"channels": 2,
						"channel_layout": "stereo",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "1308077"
						}
					},
					{
						"index": 10,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "Main",
						"codec_type": "video",
						"codec_time_base": "0/2",
						"codec_tag_string": "[27][0][0][0]",
						"codec_tag": "0x001b",
						"width": 960,
						"height": 540,
						"coded_width": 960,
						"coded_height": 540,
						"has_b_frames": 1,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "16:9",
						"pix_fmt": "yuv420p",
						"level": 31,
						"color_range": "tv",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "false",
						"nal_length_size": "0",
						"r_frame_rate": "30000/1001",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "1927853"
						}
					},
					{
						"index": 11,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/48000",
						"codec_tag_string": "[15][0][0][0]",
						"codec_tag": "0x000f",
						"sample_fmt": "fltp",
						"sample_rate": "48000",
						"channels": 2,
						"channel_layout": "stereo",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "1927853"
						}
					},
					{
						"index": 12,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "Main",
						"codec_type": "video",
						"codec_time_base": "0/2",
						"codec_tag_string": "[27][0][0][0]",
						"codec_tag": "0x001b",
						"width": 960,
						"height": 540,
						"coded_width": 960,
						"coded_height": 540,
						"has_b_frames": 1,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "16:9",
						"pix_fmt": "yuv420p",
						"level": 31,
						"color_range": "tv",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "false",
						"nal_length_size": "0",
						"r_frame_rate": "30000/1001",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "2650941"
						}
					},
					{
						"index": 13,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/48000",
						"codec_tag_string": "[15][0][0][0]",
						"codec_tag": "0x000f",
						"sample_fmt": "fltp",
						"sample_rate": "48000",
						"channels": 1,
						"channel_layout": "mono",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "2650941"
						}
					},
					{
						"index": 14,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "Main",
						"codec_type": "video",
						"codec_time_base": "0/2",
						"codec_tag_string": "[27][0][0][0]",
						"codec_tag": "0x001b",
						"width": 1280,
						"height": 720,
						"coded_width": 1280,
						"coded_height": 720,
						"has_b_frames": 1,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "16:9",
						"pix_fmt": "yuv420p",
						"level": 31,
						"color_range": "tv",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "false",
						"nal_length_size": "0",
						"r_frame_rate": "30000/1001",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "3477293"
						}
					},
					{
						"index": 15,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/48000",
						"codec_tag_string": "[15][0][0][0]",
						"codec_tag": "0x000f",
						"sample_fmt": "fltp",
						"sample_rate": "48000",
						"channels": 2,
						"channel_layout": "stereo",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/90000",
						"start_pts": 9009,
						"start_time": "0.100100",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						},
						"tags": {
							"variant_bitrate": "3477293"
						}
					}
				],
				"format": {
					"filename": "http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8",
					"nb_streams": 16,
					"nb_programs": 8,
					"format_name": "hls,applehttp",
					"format_long_name": "Apple HTTP Live Streaming",
					"start_time": "0.100100",
					"duration": "5365.000000",
					"size": "940",
					"bit_rate": "1",
					"probe_score": 100
				}
			}`),
			wantErr: false,
		},
		{
			name: "dash",
			args: args{
				url: "http://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest(format=mpd-time-csf)",
			},
			want: encodeFFProbeJson(`{
				"streams": [
					{
						"index": 0,
						"codec_name": "h264",
						"codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
						"profile": "High",
						"codec_type": "video",
						"codec_time_base": "166667/10000000",
						"codec_tag_string": "avc1",
						"codec_tag": "0x31637661",
						"width": 1920,
						"height": 1080,
						"coded_width": 1920,
						"coded_height": 1080,
						"has_b_frames": 1,
						"sample_aspect_ratio": "1:1",
						"display_aspect_ratio": "16:9",
						"pix_fmt": "yuv420p",
						"level": 40,
						"color_range": "tv",
						"color_space": "bt709",
						"color_transfer": "bt709",
						"color_primaries": "bt709",
						"chroma_location": "left",
						"refs": 1,
						"is_avc": "true",
						"nal_length_size": "4",
						"r_frame_rate": "5000000/166667",
						"avg_frame_rate": "5000000/166667",
						"time_base": "1/10000000",
						"start_pts": 333333,
						"start_time": "0.033333",
						"bit_rate": "4494772",
						"bits_per_raw_sample": "8",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						}
					},
					{
						"index": 1,
						"codec_name": "aac",
						"codec_long_name": "AAC (Advanced Audio Coding)",
						"profile": "LC",
						"codec_type": "audio",
						"codec_time_base": "1/44100",
						"codec_tag_string": "mp4a",
						"codec_tag": "0x6134706d",
						"sample_fmt": "fltp",
						"sample_rate": "44100",
						"channels": 2,
						"channel_layout": "stereo",
						"bits_per_sample": 0,
						"r_frame_rate": "0/0",
						"avg_frame_rate": "0/0",
						"time_base": "1/10000000",
						"start_pts": 0,
						"start_time": "0.000000",
						"bit_rate": "125448",
						"disposition": {
							"default": 0,
							"dub": 0,
							"original": 0,
							"comment": 0,
							"lyrics": 0,
							"karaoke": 0,
							"forced": 0,
							"hearing_impaired": 0,
							"visual_impaired": 0,
							"clean_effects": 0,
							"attached_pic": 0,
							"timed_thumbnails": 0
						}
					}
				],
				"format": {
					"filename": "http://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest(format=mpd-time-csf)",
					"nb_streams": 2,
					"nb_programs": 1,
					"format_name": "dash",
					"format_long_name": "Dynamic Adaptive Streaming over HTTP",
					"start_time": "0.000000",
					"duration": "634.000000",
					"size": "12843",
					"bit_rate": "162",
					"probe_score": 100
				}
			}`),
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ProbeStream(context.Background(), tt.args.url)
			if (err != nil) != tt.wantErr {
				t.Errorf("ProbeStream() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("ProbeStream() = %v, want %v", got, tt.want)
			}
		})
	}
}
